// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-3cL0D6gldPJik3hxxjl_ZSTSNW0n9KQ',
    appId: '1:205425873337:web:f3c7c285ed73ad7dc2e668',
    messagingSenderId: '205425873337',
    projectId: 'jiacarinventory',
    authDomain: 'jiacarinventory.firebaseapp.com',
    storageBucket: 'jiacarinventory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbaBqYVTgtZFodI0jUsfCchQL9BkRW0Xc',
    appId: '1:205425873337:android:7254ee93daddf161c2e668',
    messagingSenderId: '205425873337',
    projectId: 'jiacarinventory',
    storageBucket: 'jiacarinventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxgBLygibQ2Fie_lMbKao5hHHTtIlKOQ0',
    appId: '1:205425873337:ios:8aec2f690329fe48c2e668',
    messagingSenderId: '205425873337',
    projectId: 'jiacarinventory',
    storageBucket: 'jiacarinventory.firebasestorage.app',
    iosBundleId: 'my.tarc.edu.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxgBLygibQ2Fie_lMbKao5hHHTtIlKOQ0',
    appId: '1:205425873337:ios:8aec2f690329fe48c2e668',
    messagingSenderId: '205425873337',
    projectId: 'jiacarinventory',
    storageBucket: 'jiacarinventory.firebasestorage.app',
    iosBundleId: 'my.tarc.edu.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-3cL0D6gldPJik3hxxjl_ZSTSNW0n9KQ',
    appId: '1:205425873337:web:8662bfb657f0baccc2e668',
    messagingSenderId: '205425873337',
    projectId: 'jiacarinventory',
    authDomain: 'jiacarinventory.firebaseapp.com',
    storageBucket: 'jiacarinventory.firebasestorage.app',
  );

}